# Generated by Django 5.2 on 2025-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.FloatField()),
                ('bath', models.FloatField()),
                ('sqft', models.FloatField()),
                ('pricePerSf', models.FloatField()),
                ('lotArea', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zipCode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('lotAreaType', models.CharField(max_length=20)),
                ('homeType', models.CharField(max_length=30)),
                ('predicted_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
